apt-get -y install htop
apt-get -y install vim-nox
apt-get -y install tmux
apt-get -y install git
apt-get -y install gnuradio
apt-get -y install gr-hpsdr
apt-get -y install cmake
apt-get -y install libhdf5-dev
apt-get -y install python-mako
apt-get -y install python-numpy
apt-get -y install python-pkgconfig
apt-get -y install python-dev
apt-get -y install python-setuptools
apt-get -y install libhdf5
apt-get -y install python-h5py
apt-get -y install python-numpy
apt-get -y install python-packaging
apt-get -y install python
apt-get -y install python-dateutil
apt-get -y install python-tz
apt-get -y install python-six
apt-get -y install libgnuradio-uhd
apt-get -y install python-matplotlib
apt-get -y install python-pandas
apt-get -y install python-pytest
apt-get -y install python-scipy
apt-get -y install python-watchdog
apt-get -y install python-pip
pip install sounddevice
